export enum NotificationType {
  // Quote domain
  QUOTE_CREATED = "QUOTE_CREATED",
  QUOTE_UPDATED = "QUOTE_UPDATED",
  QUOTE_DELETED = "QUOTE_DELETED",
  QUOTE_EXPIRED = "QUOTE_EXPIRED",
  QUOTE_FOR_SHIPMENT = "QUOTE_FOR_SHIPMENT",
  SPOT_QUOTE_CREATED = "SPOT_QUOTE_CREATED",
  
  // Shipment domain  
  SHIPMENT_CREATED = "SHIPMENT_CREATED",
  SHIPMENT_UPDATED = "SHIPMENT_UPDATED",
  SHIPMENT_DELETED = "SHIPMENT_DELETED",
  SHIPMENT_STATUS_CHANGED = "SHIPMENT_STATUS_CHANGED",
  
  // AddressBook domain
  ADDRESSBOOK_CREATED = "ADDRESSBOOK_CREATED",
  ADDRESSBOOK_UPDATED = "ADDRESSBOOK_UPDATED",
  ADDRESSBOOK_DELETED = "ADDRESSBOOK_DELETED",
  
  // System
  SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT",
  REMINDER = "REMINDER"
}
