export enum BondType {
    T_E_BOND = "T_E_BOND",
    IT_BOND = "IT_BOND"
}

export enum ContactKey {
    EMAIL = "EMAIL", 
    FAX_NUMBER = "FAX_NUMBER", 
    PHONE = "PHONE"
}

export enum LimitedAccessType {
    OTHERS = "OTHERS",
    CONSTRUCTION_SITE = "CONSTRUCTION_SITE", 
    AMUSEMENT_PARK = "AMUSEMENT_PARK", 
    FARM_COUNTRY_CLUB_ESTATE = "FARM_COUNTRY_CLUB_ESTATE", 
    SCHOOL_UNIVERSITY = "SCHOOL_UNIVERSITY", 
    GROCERY_RETAIL_LOCATIONS = "GROCERY_RETAIL_LOCATIONS", 
    INDIVIDUAL_STORAGE_UNIT = "INDIVIDUAL_STORAGE_UNIT", 
    PLACE_OF_WORSHIP = "PLACE_OF_WORSHIP", 
    SECURED_LOCATIONS_DELIVERY = "SECURED_LOCATIONS_DELIVERY", 
    PLAZA_MALL_OR_STORES_WITH_PARKING_LOT_STREET_ACCESS = "PLAZA_MALL_OR_STORES_WITH_PARKING_LOT_STREET_ACCESS"
}
