export enum ShipmentType {
  PACKAGE = 'PACKAGE',
  PALLET = 'PALLET',
  COURIER_PAK = 'COURIER_PAK',
  STANDARD_FTL = 'STANDARD_FTL',
  SPOT_LTL = 'SPOT_LTL',
  SPOT_FTL = 'SPOT_FTL',
  TIME_CRITICAL = 'TIME_CRITICAL',
}